version: '3.2'

services:
    web:
        image: danielaalvarado/special-olympics-web
        deploy:
            replicas: 3
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s
            endpoint_mode: dnsrr
    proxy:
        image: haproxytech/haproxy-debian:2.0
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - type: bind
              source: /etc/haproxy
              target: /etc/haproxy
              read_only: true
        dns: 127.0.0.11
        deploy:
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s
            placement:
                constraints: [node.role == manager]